-- MarginBusiness Leads v3.1 — customer access, plans and protected AI credits
-- Repeat-safe. Does not delete customer data.
create extension if not exists pgcrypto;

create table if not exists public.platform_admins(
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.workspace_subscriptions(
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  plan_code text not null default 'trial',
  status text not null default 'trialing',
  billing_interval text,
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  trial_ends_at timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_credit_balances(
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  balance integer not null default 0 check(balance >= 0),
  lifetime_granted integer not null default 0,
  lifetime_used integer not null default 0,
  period_granted integer not null default 0,
  period_used integer not null default 0,
  period_started_at timestamptz not null default now(),
  period_ends_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_ledger(
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  amount integer not null,
  balance_after integer not null,
  reason text not null,
  reference_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.workspaces add column if not exists account_status text not null default 'active';
alter table public.workspaces add column if not exists signup_source text;
alter table public.workspaces add column if not exists trial_started_at timestamptz;
alter table public.workspaces add column if not exists trial_ends_at timestamptz;
alter table public.workspaces add column if not exists max_users integer not null default 1;
alter table public.workspaces add column if not exists max_leads integer not null default 25;
alter table public.workspaces add column if not exists ai_daily_limit integer not null default 10;

insert into public.workspace_subscriptions(workspace_id,plan_code,status,trial_ends_at)
select id,'trial','trialing',coalesce(trial_ends_at,now()+interval '14 days') from public.workspaces
on conflict(workspace_id) do nothing;

insert into public.workspace_credit_balances(workspace_id,balance,lifetime_granted,period_granted,period_ends_at)
select id,10,10,10,coalesce(trial_ends_at,now()+interval '14 days') from public.workspaces
on conflict(workspace_id) do nothing;

create index if not exists credit_ledger_workspace_created_idx on public.credit_ledger(workspace_id,created_at desc);
create index if not exists workspace_subscriptions_status_idx on public.workspace_subscriptions(status,updated_at desc);

alter table public.platform_admins enable row level security;
alter table public.workspace_subscriptions enable row level security;
alter table public.workspace_credit_balances enable row level security;
alter table public.credit_ledger enable row level security;

create or replace function public.is_platform_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.platform_admins where user_id=(select auth.uid()))
$$;

create or replace function public.consume_workspace_credits(
  p_workspace_id uuid,
  p_user_id uuid,
  p_amount integer,
  p_reason text,
  p_reference_id text default null,
  p_metadata jsonb default '{}'::jsonb
) returns table(ok boolean,balance integer,message text)
language plpgsql security definer set search_path=public as $$
declare v_balance integer; v_today_used integer;
begin
  if p_amount is null or p_amount <= 0 then return query select false,0,'Invalid credit amount'; return; end if;
  if not exists(select 1 from public.workspace_members where workspace_id=p_workspace_id and user_id=p_user_id)
     and not exists(select 1 from public.workspaces where id=p_workspace_id and owner_id=p_user_id) then
    return query select false,0,'Workspace access denied'; return;
  end if;
  if exists(select 1 from public.workspaces where id=p_workspace_id and account_status <> 'active') then
    return query select false,0,'Workspace is suspended'; return;
  end if;
  select count(*) into v_today_used from public.credit_ledger
   where workspace_id=p_workspace_id and amount<0 and created_at>=date_trunc('day',now());
  if abs(v_today_used) >= coalesce((select ai_daily_limit from public.workspaces where id=p_workspace_id),10) then
    return query select false,coalesce((select balance from public.workspace_credit_balances where workspace_id=p_workspace_id),0),'Daily AI limit reached'; return;
  end if;
  update public.workspace_credit_balances set balance=balance-p_amount,lifetime_used=lifetime_used+p_amount,
    period_used=period_used+p_amount,updated_at=now()
   where workspace_id=p_workspace_id and balance>=p_amount returning balance into v_balance;
  if v_balance is null then
    return query select false,coalesce((select balance from public.workspace_credit_balances where workspace_id=p_workspace_id),0),'Not enough Margin Credits'; return;
  end if;
  insert into public.credit_ledger(workspace_id,user_id,amount,balance_after,reason,reference_id,metadata)
  values(p_workspace_id,p_user_id,-p_amount,v_balance,p_reason,p_reference_id,coalesce(p_metadata,'{}'::jsonb));
  return query select true,v_balance,'Credits reserved';
end $$;

create or replace function public.grant_workspace_credits(
 p_workspace_id uuid,p_amount integer,p_reason text,p_reference_id text default null,p_metadata jsonb default '{}'::jsonb
) returns integer language plpgsql security definer set search_path=public as $$
declare v_balance integer;
begin
 if p_amount is null or p_amount <= 0 then raise exception 'Invalid credit amount'; end if;
 insert into public.workspace_credit_balances(workspace_id,balance,lifetime_granted,period_granted)
 values(p_workspace_id,p_amount,p_amount,p_amount)
 on conflict(workspace_id) do update set balance=public.workspace_credit_balances.balance+p_amount,
 lifetime_granted=public.workspace_credit_balances.lifetime_granted+p_amount,
 period_granted=public.workspace_credit_balances.period_granted+p_amount,updated_at=now()
 returning balance into v_balance;
 insert into public.credit_ledger(workspace_id,amount,balance_after,reason,reference_id,metadata)
 values(p_workspace_id,p_amount,v_balance,p_reason,p_reference_id,coalesce(p_metadata,'{}'::jsonb));
 return v_balance;
end $$;

-- Customer policies
do $$
declare table_name text;
begin
  foreach table_name in array array['workspace_subscriptions','workspace_credit_balances','credit_ledger'] loop
    execute format('drop policy if exists "workspace members read %s" on public.%I',table_name,table_name);
  end loop;
end $$;
drop policy if exists "admins read platform admins" on public.platform_admins;
create policy "admins read platform admins" on public.platform_admins for select to authenticated using(user_id=(select auth.uid()) or public.is_platform_admin());
create policy "workspace members read workspace_subscriptions" on public.workspace_subscriptions for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "workspace members read workspace_credit_balances" on public.workspace_credit_balances for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "workspace members read credit_ledger" on public.credit_ledger for select to authenticated using(public.is_workspace_member(workspace_id));
