-- MarginBusiness Leads v3.0 repeat-safe beta migration
-- Safe to run more than once. It does not delete tables or lead data.

create extension if not exists pgcrypto;

create table if not exists public.workspaces(
  id uuid primary key default gen_random_uuid(), name text not null, slug text unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  plan text not null default 'beta', created_at timestamptz not null default now()
);
create table if not exists public.workspace_members(
  workspace_id uuid references public.workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  role text not null default 'owner', created_at timestamptz not null default now(),
  primary key(workspace_id,user_id)
);
create table if not exists public.campaigns(
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null, source text, import_profile text, status text default 'active', settings jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.leads(
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade,
  campaign_id uuid references public.campaigns(id) on delete set null, company text, contact_name text, role text, email text,
  website text, category text, product text, status text default 'new', fit_score integer default 0,
  data jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.activity_logs(
  id bigint generated by default as identity primary key, workspace_id uuid references public.workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null, event_type text not null, entity_type text, entity_id text,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz default now()
);

alter table public.workspaces add column if not exists daily_send_limit integer not null default 100;
alter table public.workspaces add column if not exists monthly_ai_limit integer not null default 250;
alter table public.workspaces add column if not exists sender_name text;
alter table public.workspaces add column if not exists sender_email text;
alter table public.workspaces add column if not exists updated_at timestamptz not null default now();

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.campaigns enable row level security;
alter table public.leads enable row level security;
alter table public.activity_logs enable row level security;

create index if not exists workspace_members_user_idx on public.workspace_members(user_id);
create index if not exists campaigns_workspace_idx on public.campaigns(workspace_id,updated_at desc);
create index if not exists leads_workspace_idx on public.leads(workspace_id,updated_at desc);
create index if not exists leads_campaign_idx on public.leads(campaign_id);
create index if not exists activity_logs_workspace_created_idx on public.activity_logs(workspace_id,created_at desc);
create index if not exists activity_logs_workspace_event_idx on public.activity_logs(workspace_id,event_type,created_at desc);

create or replace function public.is_workspace_member(wid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.workspace_members where workspace_id=wid and user_id=(select auth.uid()))
      or exists(select 1 from public.workspaces where id=wid and owner_id=(select auth.uid()))
$$;
create or replace function public.workspace_role(wid uuid)
returns text language sql stable security definer set search_path=public as $$
  select coalesce(
    (select role from public.workspace_members where workspace_id=wid and user_id=(select auth.uid()) limit 1),
    (select 'owner' from public.workspaces where id=wid and owner_id=(select auth.uid()) limit 1)
  )
$$;

-- Policies are deliberately replaced so this file remains repeat-safe.
drop policy if exists "workspace members can view workspaces" on public.workspaces;
drop policy if exists "owners can create workspaces" on public.workspaces;
drop policy if exists "members can view memberships" on public.workspace_members;
drop policy if exists "owners and admins manage memberships" on public.workspace_members;
drop policy if exists "members manage campaigns" on public.campaigns;
drop policy if exists "members read campaigns" on public.campaigns;
drop policy if exists "operators manage campaigns" on public.campaigns;
drop policy if exists "members manage leads" on public.leads;
drop policy if exists "members read leads" on public.leads;
drop policy if exists "operators manage leads" on public.leads;
drop policy if exists "members view logs" on public.activity_logs;
drop policy if exists "members create logs" on public.activity_logs;

create policy "workspace members can view workspaces" on public.workspaces for select to authenticated using(public.is_workspace_member(id));
create policy "owners can create workspaces" on public.workspaces for insert to authenticated with check(owner_id=(select auth.uid()));
create policy "members can view memberships" on public.workspace_members for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "owners and admins manage memberships" on public.workspace_members for all to authenticated
  using(public.workspace_role(workspace_id) in ('owner','admin'))
  with check(public.workspace_role(workspace_id) in ('owner','admin'));
create policy "members read campaigns" on public.campaigns for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "operators manage campaigns" on public.campaigns for all to authenticated
  using(public.workspace_role(workspace_id) in ('owner','admin','operator'))
  with check(public.workspace_role(workspace_id) in ('owner','admin','operator'));
create policy "members read leads" on public.leads for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "operators manage leads" on public.leads for all to authenticated
  using(public.workspace_role(workspace_id) in ('owner','admin','operator'))
  with check(public.workspace_role(workspace_id) in ('owner','admin','operator'));
create policy "members view logs" on public.activity_logs for select to authenticated using(public.is_workspace_member(workspace_id));
create policy "members create logs" on public.activity_logs for insert to authenticated
  with check(public.is_workspace_member(workspace_id) and user_id=(select auth.uid()));
